### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by aleeessio** [Bbalduzz/Kitaboo-PDF-Downloader#3]
```
  File "/Kitaboo-PDF-Downloader/zncDL.py", line 23, in <module>
    toc_req = SESSION.get(f'{BASE_URL}/content.opf')
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 387, in request
    self.putheader(header, value)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 301, in putheader
    super().putheader(header, *values)
  File "/usr/lib/python3.10/http/client.py", line 1260, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value
```

Maybe cookie's stucture has changed:
```
CloudFront-Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vd2VicmVhZGVyLnphbmljaGVsbGkuaXQvMTAxNTAzL2h0bWw1LyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2ODk2NDc4MTh9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn0sIkRhdGVHcmVhdGVyVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg5NjM2NDE4fX19XX0=; CloudFront-Signature=Us3yzx7eSVk09UWSkoXzP-zcUMF5dL-rZZDXjtYgM9U924RXtebplGyA7SBRAcjUDmM~2nJ4ayvR4gay5P6BfBgnORbD~vj66xfXSI1pRcsxUHaK3DGVTZqn3QqTIvI7jyAyJSLBTqHCK7Omkwy1Qj-bQ6wOKC9XzV48RkpNtnTliMWZP9WywSwlsTOifaQGFH4oSRRACIRVplLdlw-Q0FJH53-HJKQ9W6xPKUslxYypV~EUNIrlYNzsYaFYt6cBxarH20BG6GqD2BH~j4pCJ4jrOAYec1TOk0m~sj9uuINLr97QzEboY6djLvf3XuY~ZvclJsv~nx9G2bvbOB5nKA__; CloudFront-Key-Pair-Id=APKAJLZIBANJDUWZO6EA; myz_session=10123225.64b5d078f14f76.89606121; OptanonConsent=isGpcEnabled=0&datestamp=Tue+Jul+18+2023+01%3A47%3A47+GMT%2B0200+(Ora+legale+dell%E2%80%99Europa+centrale)&version=202303.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=5d56a841-1aef-473e-9639-f3ba0122e040&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0003%3A1%2CC0004%3A1%2CC0002%3A1&geolocation=IT%3B62&AwaitingReconsent=false; OptanonAlertBoxClosed=2023-07-17T23:36:35.794Z; stack2=["my.zanichelli.it","webreader.zanichelli.it"]; _ga_FL8QBN8HHQ=GS1.1.1689636995.1.1.1689637667.0.0.0; _ga=GA1.1.944069098.1689636996; _ga_M3CF5M6GK8=GS1.1.1689636995.1.1.1689637016.0.0.0; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvaWRwLnphbmljaGVsbGkuaXRcL3Y0XC9sb2dpbiIsImlhdCI6MTY4OTYzNjk5OCwiZXhwIjoxNjkwMjQxNzk4LCJuYmYiOjE2ODk2MzY5OTgsImp0aSI6IjdLZHhDN2Ywb2JUckF4R0UiLCJzdWIiOjE3MTcyLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiaWQiOjE3MTcyLCJuYW1lIjoiSmFrb3YgQXNhbiIsImdpdmVuX25hbWUiOiJKYWtvdiIsImZhbWlseV9uYW1lIjoiQXNhbiIsInByZWZlcnJlZF91c2VybmFtZSI6Impha292YXNhbi4xMDNAZ21haWwuY29tIiwiZW1haWwiOiJqYWtvdmFzYW4uMTAzQGdtYWlsLmNvbSIsImlzX3ZlcmlmaWVkIjoxLCJpc19lbXBsb3llZSI6MCwiaXNfbXl6YW5pY2hlbGxpIjoxLCJjcmVhdGVkX2F0IjoiMjAyMi0wMS0wMSAxNToxMjoxMyIsInVwZGF0ZWRfYXQiOm51bGwsImxhc3RfYWN0aXZpdHlfYXQiOiIyMDIzLTA3LTE3IDIzOjE2OjMxIiwicm9sZXMiOlt7ImlkIjoxNTg0MSwidXNlcl9pZCI6MTcxNzIsImRlcGFydG1lbnRfaWQiOm51bGwsInJvbGVfaWQiOjQyLCJyb2xlTmFtZSI6Ik1ZWl9VU0VSIn0seyJpZCI6Njc2ODU1LCJ1c2VyX2lkIjoxNzE3MiwiZGVwYXJ0bWVudF9pZCI6bnVsbCwicm9sZV9pZCI6MjMsInJvbGVOYW1lIjoiTVlaX1NUVURFTlRFIn1dLCJhdHRyaWJ1dGVzIjpbXSwibXl6Ijp7ImlkIjoxMjY3MDcwLCJpc0NvbmZpcm1lZCI6dHJ1ZSwiaXNBcHByb3ZlZCI6dHJ1ZSwiaXNBdXRob3JpemVkQnlQYXJlbnQiOnRydWV9fQ.E9DVa2kOMvZmjV1mvNlyQJk3RDWZJb7l5GGgZT9EHQKEKxWRJ1Hf56siQF9Ny-01vMjX4jputepNJfoFB-2OA1OtGpr64XLBji5gg8aDSRDCw8YqmopVcZcWRduAMC53CAEFugu_HIfZuqS9gmpK6NiNgwtboM6JNfE4evT3UpJMil6lXA0RI_f11EAwKxSdujWzQF4ttW2x8P46M7LSGGAjrVLRkYm-jafM5-xQ-Ncqxifu4z1MAX6WPtZ0-SLhYdIB7FhmiBwyBodbN9wGJeb7f-uc2gMbCyCOMgBLqq8fChOZNeSLl1COhvf4OJoKrwu-MFSOoN7MWpLTjy0z5rXiYi1cOERY796Z0eWBz10MVV49YsoLBEve1PlvC9n9XrZhxIyv8-MVS2O5j-w3JbaNlyQXzgWYSHYqInZLzPgmCH1rjVUqRXY_qPHfdXxtjru_ybiZE-Rf5upP7z5R7gYVG8u_lZ4Iy_Tj5xtF-izHMv38YfI7xgrI2jDMpX8rpEaMx-6nk-juR2YbujrJJuyMHpUkn14MTIAtWg5l7-ORHfnIWKq4npfDvWgR_eTnJMIF0dFhsljd3UjEArVRoSgo7l0CxmnssllEQDw2MZR95MfeoDPLYKzS656LpqJB90ToZwtn7kvxIlBm6xjPQ7MYIfMMmAED7--XFv0Syt0; myz_token=kmjlwsdpyd; lastVisitedHosts={"17172":["my.zanichelli.it"]}; _ga_HLT0GPY74V=GS1.1.1689637018.1.1.1689637667.0.0.0; _ga_H75ERVB8TD=GS1.1.1689637018.1.1.1689637665.0.0.0
```

**Comment by Bbalduzz** [comment]
ciao! non riesco a riprodurre il tuo errore. 
Da dove hai preso i cookies? Perchè la struttura è effettivamente diversa.
Comunque sia ho aggiunto una funzione che prende qualsiasi stringa di cookies (con la struttura giusta o meno) e crea il dizionario di cookies richiesto :)
Fammi sapere se incotri altri problemi.

**Comment by aleeessio** [comment]
> 
I cookie li ho presi sempre dal toc.xml
![Immagine 2023-07-18 143500](https://github.com/Bbalduzz/Kitaboo-PDF-Downloader/assets/87971492/78ba3b4d-e2e3-4e67-85f5-9f9a1f56f692)

Ora però c'è ques'altro errore:
```
python3 zncDL.py 
Traceback (most recent call last):
  File "/Kitaboo-PDF-Downloader/zncDL.py", line 27, in <module>
    COOKIE = {'Cookie': parse_cookie(cookie)}
  File "/Kitaboo-PDF-Downloader/zncDL.py", line 22, in parse_cookie
    if match := re.search(pattern, cookie_string):
NameError: name 're' is not defined
```

**Comment by Bbalduzz** [comment]
si scusa mi ero dimenticato di aggiungerlo. Ora è sistemato

**Comment by aleeessio** [comment]
> si scusa mi ero dimenticato di aggiungerlo. Ora è sistemato

Si ho eliminato perché sono riuscito a farlo andare apparentemente, aggiungi  anche la libreria lxml per bs4 che era richiesta :)
